name: mahjong_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  camera: ^0.10.5+9
  tflite_flutter: ^0.11.0
  image: ^4.1.7
  flutter_isolate: ^2.0.4
  http: ^1.2.1
  shared_preferences: ^2.2.3
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
